### ISSUE TITLE
Background audio still doesnt work on ios 9.0.2. Any plans to fix?

### ISSUE THREAD

**Issue by adammusic** [eni9889/YT-PP-Issues#100]
Updated to current YT++ version.

**Comment by eni9889** [comment]
Do you have Mikoto installed?

**Comment by adammusic** [comment]
Yes. I also completely lost my next video/previous video controls on the video overlay. I still have the skip/rwd however many seconds icons

**Comment by eni9889** [comment]
Mikoto interferes with YouTube background playback. You need to  go  into Mikoto settings and  disable  background playback

**Comment by adammusic** [comment]
👍🏽
