### ISSUE TITLE
Ad Removal Won't Work

### ISSUE THREAD

**Issue by Gresh66** [eni9889/YT-PP-Issues#104]
I paid the $7 to remove all ads and I'm still getting ads on all your tweaks. The only thing that seems to work is tweeting to remove ads, and yes I've made sure I'm signed in to the account I used to pay.

**Comment by eni9889** [comment]
https://blog.unlimapps.com/2017/06/05/regarding-ads-and-notifications-in-tweaks-from-signing-services/
