### ISSUE TITLE
[Bug] + and - Speed buttons while playing a video does not work 

### ISSUE THREAD

**Issue by TheNightRider12** [eni9889/YT-PP-Issues#112]
iOS: 10.1.1
Jailbroken
Tweak: 1.4r-87
App: 12.38

When pressing the speed buttons in a video, they do not seem to work. The video speed seems to remain the same.

**Comment by jkister** [comment]
Confirmed iOS 933 jail broke yt++ 1.4r-87 uasharedtools 2.1r-13 app 12.38

**Comment by jkister** [comment]
Confirmed iOS 933 jail broke yt++ 1.4r-87 uasharedtools 2.1r-13 app 12.38

**Comment by TheNightRider12** [comment]
Issue has been fixed on Jailbreak.
