### ISSUE TITLE
Crash when trying to sign in to YT account (YT++ Premium) (12.44.16) [Side loaded]

### ISSUE THREAD

**Issue by UCDHIUS** [eni9889/YT-PP-Issues#128]
Crash when trying to sign in to YT account (YT++ Premium)

iPhone X (iOS 11.1.1)

Side loaded via Cydia impactor

App version 12.44.16 (Tweak 1.4r-88)

Any walk arounds or fixes?

Thanks

**Comment by iPhoNewsRO** [comment]
same, iphone x 11.2 beta 3
crash on sign in button (home, settings, welcome page)
