### ISSUE TITLE
Updating issue. 

### ISSUE THREAD

**Issue by Dershowitz011** [eni9889/YT-PP-Issues#138]
Every time I try to update over existing YT++ app, it says application identifier doesn't match with what app that is YT++ I've installed. I hadn't changed the bundle identifier at all. I had to uninstall the existing app n re install fresh. This happened last time too. Please fix. Thanks. I use ios-deploy to sideload after signing. Ios 10.3.1. iPhone 6s Plus.

**Comment by eni9889** [comment]
If you are changing the signing profile  you  will need to delete and  re-install
