### ISSUE TITLE
[FEATURE] Downloaded videos sort order (Ascending/Descending Download Date)

### ISSUE THREAD

**Issue by darrickteng** [eni9889/YT-PP-Issues#15]
YT++ currently has 2 sort orders:
1. Video Title
2. Download Date

The download date sort order currently does newest on top, oldest on the bottom of the list

Could we have a reverse sorting of this where the old videos are on top and the newest videos are on the bottom?

Since playing downloaded videos goes from the top of the list to the bottom of the list, it is sometimes useful for the videos to play from oldest downloaded to newest downloaded

**Comment by D3m3rion** [comment]
I would like to see a much enhanced download section with the ability to make folders, custom sort order, etc
