### ISSUE TITLE
[BUG] File Merging broken

### ISSUE THREAD

**Issue by D3m3rion** [eni9889/YT-PP-Issues#22]
When I am downloading videos and let YouTube run in the background, the file merging doesn't work (correctly).
There's no problem at the download itself, but YouTube appearently needs to be open in the downloaded section when the file merging takes place. Otherwise the output consists of the video first, without sound, and the sound attached at the end.

I am using an iPhone 6s on iOS 10.2 using the latest version of YT and YT++ (bug occurs on older versions aswell).

**Comment by JMccormick264** [comment]
Are you still having this with the latest Tweak update?

**Comment by D3m3rion** [comment]
Yes, I do.

**Comment by D3m3rion** [comment]
Can also reproduce this on my iPad mini 2, with iOS 10.2 and the latest version of both, yt and yt++

**Comment by eni9889** [comment]
This seems to happen when no audio is present and I can't seem to repro but I will continue to look into it
