### ISSUE TITLE
[Bug]  Cannot see the download button on the latest YouTube version 12.14

### ISSUE THREAD

**Issue by Aakash99rocks** [eni9889/YT-PP-Issues#24]
iOS: 10.2 
Type: Jailbroken
YouTube: 12.14
Tweak: 1.4r-35 
Device: Iphone 6S
As the title says, I'm not able to see the download button in the official YouTube 12.14 app, after I updated it yesterday I'm not able to see the download button under the share ++ menu however when I click the 3 dots that are vertically aligned I'm able to see the download button

**Comment by JMccormick264** [comment]
Issue has been fixed. Closing.
