### ISSUE TITLE
[BUG] Videos starting over at Internet (dis)connection

### ISSUE THREAD

**Issue by D3m3rion** [eni9889/YT-PP-Issues#32]
So, there is this bug where downloaded Youtube videos restart from the beginning everytime you connect or disconnect to/ from the Internet.
This basically forces me to turn on Airplane Mode to watch a video.
Honestly, this is getting on my nerves, and I would like to see this fixed asap, although I know that of course, everybody has different bugs they would love to see fixed haha ;)
Has been happening for a few versions, might be the case, that it's an iOS 10 thing. I remember everything being okay while I was on iOS 9.
I'm using an iPhone 6s running iOS 10.2 with the latest versions of YT and YT++.
Exact same thing happening on my iPad Mini 2, same versions.

**Comment by SeMoOo** [comment]
@D3m3rion I have had this issue since iOS 8.4 (i guess) when I started using YT++. Till today, The issue still exist. I hope the developer @eni9889 fix it soon. 

There is another post for this bug. 

https://github.com/eni9889/YT-PP-Issues/issues/4

**Comment by peatymasta** [comment]
I've had this issue too. Happens whenever I disconnect or connect from a wifi network.

**Comment by D3m3rion** [comment]
Fixed via 1.4r-72
