### ISSUE TITLE
Sharing channel seems crashing the App (only channel, work nice with sharing a video)

### ISSUE THREAD

**Issue by Sam-Ryan** [eni9889/YT-PP-Issues#46]
Yo I provide the following crashlog for ytpp
[Package List.txt](https://github.com/eni9889/YT-PP-Issues/files/1185391/Package.List.txt)
[YouTube-2017-07-30-024750.syslog.txt](https://github.com/eni9889/YT-PP-Issues/files/1185392/YouTube-2017-07-30-024750.syslog.txt)
[YouTube-2017-07-30-024750.symbolicated.ips.txt](https://github.com/eni9889/YT-PP-Issues/files/1185394/YouTube-2017-07-30-024750.symbolicated.ips.txt)

Warmly Ryan

**Comment by eni9889** [comment]
Hi,

How do you go about sharing a channel?

**Comment by JMccormick264** [comment]
@eni9889 Go to a channel -> 3 dots at the top, then "Share"

**Comment by eni9889** [comment]
This should be fixed in the latest version on beta.unlimapps.com if not please send me the link to a channel that is crashing

**Comment by JMccormick264** [comment]
@Sam-Ryan Update to the latest tweak and see if it fixes the issue for you. Seems to have for me.

**Comment by Sam-Ryan** [comment]
@Eni9889 , @JMccormick264 fixed With The new update. Thanks Eni 😍
