### ISSUE TITLE
[BUG] Info Card not showing up?

### ISSUE THREAD

**Issue by AP0II0** [eni9889/YT-PP-Issues#50]
The info card on YouTube is showing up at all..
Pretty sure its coming from this tweak. Hopefully I'm not the only one.

**Comment by AP0II0** [comment]
Forgot...
iOS: 10.1.1
App: 12.29
Tweak: 1.4r-59
Type: Jailbreak

**Comment by JMccormick264** [comment]
What do you mean by "Info Card"?

**Comment by AP0II0** [comment]
Example Picture:
https://lh6.googleusercontent.com/aL0K52iyhGEu7JjiKzNTHuEGBdoGBeh286UtihNqnQXLHEUCjyBXK4ekCVg51IuJh6JlcN1d0pTMsbd7367kU6mqen-AgAkjAijIvG34wB5bcmVvfItKtKc9GqfTpBwisA
(The "i" in the circle icon)

**Comment by AP0II0** [comment]
Nvm its not coming from this tweak. I turned the tweak off w/ iCleaner and the icon "info card"  still didn't show. I think its a bug from the actually app. Reported it to YouTube, hopefully they can find a fix.
