### ISSUE TITLE
[Request] Higher default playback quality to 1440p

### ISSUE THREAD

**Issue by AP0II0** [eni9889/YT-PP-Issues#51]
Default Playback Quality WiFi: "1440p"
My iPhone 7 can go up to this quality on some videos.
Im lazy but makes things go quicker.

**Comment by Sam-Ryan** [comment]
Hi,
You have to search from video which is uploaded is this quality. 
Warmly 
Ryan
![image18](https://user-images.githubusercontent.com/29762494/28886322-5ec9ca20-77b9-11e7-8e2e-a9bb1ed3e7ac.png)

**Comment by D3m3rion** [comment]
@Ryan, he's talking about the default playback quality, in the ++ settings

**Comment by Sam-Ryan** [comment]
@D3m3rion I know but you cant download all video in 2160p, that's why you cannot set default quality at higher because all video are not in 2160p.
Warmly

**Comment by D3m3rion** [comment]
Not the downlaod, but the playback. And although not every video is playable in 1080p60f, you can still set the default to this value.
And this thread is to allow us to set it to 1440p or higher @Sam-Ryan

**Comment by Sam-Ryan** [comment]
Whats The goals to set this value If The video isnt playable in HD?! The same as When you play 4K on a non UHD screen.

**Comment by D3m3rion** [comment]
There are videos with that quality, and you just set the highest possible in the settings so it always automatically plays in the highest quality available
