### ISSUE TITLE
[BUG] Speed up-down buttons do not work

### ISSUE THREAD

**Issue by karaigumon** [eni9889/YT-PP-Issues#55]
[ ] iOS Version: 10.2
[ ] YouTube Version: 12.29
[ ] YT ++ Tweak Version: 1.4r-62
[ ] Crash Report: No crash
[ ] Jailbroken issue

Whenever I try to speed up or slow down the video, it doesn't work.

**Comment by Sam-Ryan** [comment]
Hi,
Works fine on Youtube 12.29 and YT ++ 1.4r-62. Try to reinstall the tweak. If it's not working try to reinstall the app.
Warmly
