### ISSUE TITLE
[Bug] YT 12.32: Hiding Selected Tabs does not work

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/YT-PP-Issues#77]
Jailbreak
iOS 10.1.1
App Version: 12.32
Tweak: 1.4r-78

Hiding Tabs does not work. I tried hiding the trending tab, and it will not hide. 

[Image 1](http://i.imgur.com/0MXI9GD.png)
[Image 2](http://i.imgur.com/5XkrRFf.png)

**Comment by eni9889** [comment]
Fixed
