### ISSUE TITLE
[Bug] YT: 12.32: Save button does not appear while some videos are playing

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/YT-PP-Issues#79]
iOS: 10.1.1
Jailbreak
YT: 12.32
Tweak: 1.4r-79

When playing a video, the "Save" button does not appear to save the video.

**Comment by JMccormick264** [comment]
Wanted to add. This does not happen for all videos. I have only found this happen during one video.

**Comment by eni9889** [comment]
@JMccormick264 can you give some screenshots and a sample video

**Comment by JMccormick264** [comment]
@eni9889 [Image](https://puu.sh/xgHRh/12342c6d6a.PNG)

[Video](https://www.youtube.com/watch?v=6ugUQN-rhaY)

**Comment by eni9889** [comment]
Does clicking on the share button work?

**Comment by JMccormick264** [comment]
Issue has been fixed. This can be closed.
