### ISSUE TITLE
youtube ++ not downloading videos

### ISSUE THREAD

**Issue by shenronX** [eni9889/YT-PP-Issues#84]
Youtube++ Not downloading videos.
(Videos from the Japanese band called "ZARD", some other music videos, and a dbz song called "Kibou No uta").

**Comment by shenronX** [comment]
https://youtu.be/3aevyrmqbY0 Here is a link to one of the songs.

**Comment by eni9889** [comment]
Some videos cannot be downloaded due to region restrictions

**Comment by shenronX** [comment]
Wait wait wait.... But I downloaded one of the videos that can't be downloaded now before, I kept pressing download again. And again and it worked before but not anymore, I think it's a glitch.
