### ISSUE TITLE
[Bug] Sign-out when playing video in Background

### ISSUE THREAD

**Issue by xela1333** [eni9889/YT-PP-Issues#85]
IOS: 10.3.3
Youtube: 12.30.12
Tweak: 1.4r-76
Sideloader: Tutu

**Comment by xela1333** [comment]
When I play a video and then put it in sleep mode or in the background, the video stops and signs me out of my account afterwords. It was not happening the day before this post.

**Comment by D3m3rion** [comment]
I can confirm this on my jailbroken device, newest versions. Background playing does not work anymore. Atleast I'm not signed out if I try it.

**Comment by Swally0323** [comment]
Also happens to me any confirmation on when thai will be fixed?

**Comment by eni9889** [comment]
Can you test latest version on beta.unlimapps.com

**Comment by xela1333** [comment]
I'm sideloading so I can not really download the latest version without jailbreaking and Cydia. Unless I can download it without jailbreaking, I'm stuck until a updated version is uploaded into Tutu.

**Comment by xela1333** [comment]
I checked with cydia impactor, and it seems to be the latest version to download as well.
