### ISSUE TITLE
Unable to sign in as the sign in option doesn't work

### ISSUE THREAD

**Issue by seunAde** [eni9889/YT-PP-Issues#91]
UATOOLS: 2.1r-101 tweak: 1.4r-76 app: 12.32.9-SL

IOS 10.3.3, iphone 7+ plus. 

For the past 2 versions including the latest above, I am unable to sign in. When I click sign in, the page to enter the details never appears. 

I have tried deleting and reinstalling but doesn't work.

**Comment by seunAde** [comment]
Phone not jail broken. Using appdb to install tweaked apps

**Comment by eni9889** [comment]
This will be fixed soon

**Comment by seunAde** [comment]
Fixed in the new update. Thank you.
