### ISSUE TITLE
Background audio isnt working..

### ISSUE THREAD

**Issue by adammusic** [eni9889/YT-PP-Issues#98]
On 9.0.3

Since that major youtube update about a week ago

**Comment by eni9889** [comment]
Which version of the tweak are you on?

**Comment by adammusic** [comment]
Current version. Up to date.

**Comment by eni9889** [comment]
Do you have Mikoto installed?

**Comment by adammusic** [comment]
Turning off background in mikoto fixed it. Background is now working. Thanks!
